name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag urlshortener:$(date +%s)
    - name: Publish the Docker image
      run: docker push mostwantedrbx/urlshortener:$(date +%s)
#       uses: bitovi/github-actions-docker-publish@v1.0.1
#       with:
#         repo_name: mostwantedrbx/urlshortener
#         docker_username: ${{ secrets.DOCKER_USERNAME }}
#         docker_password: ${{ secrets.DOCKER_PASSWORD }}

      
