name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: mostwantedrbx/urlshortener
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
#       run: docker build . --file Dockerfile --tag urlshortener:$(date +%s)
#     - name: Publish the Docker image
#       run: docker push mostwantedrbx/urlshortener:$(date +%s)
#       uses: bitovi/github-actions-docker-publish@v1.0.1
#       with:
#         repo_name: mostwantedrbx/urlshortener
#         docker_username: ${{ secrets.DOCKER_USERNAME }}
#         docker_password: ${{ secrets.DOCKER_PASSWORD }}

      
